Add dependency report generation
glencoesoftware/NGFF-Converter pull request #55
Opened 2023-11-29 09:34 UTC by sbesson

This adds the build logic to generate a report of all dependencies of the NGFF-Converter application including their licenses similar to the effort done for https://www.glencoesoftware.com/products/omeroplus/dependencies/

- add `build.gradle` target consuming https://github.com/hierynomus/license-gradle-plugin
- override and normalize dependencies as 
- add the dependency report generation to the GitHub workflow build process

A new build artifact should be generated including the dependency report in various formats (XML, JSON, HTML) for inspection. The current version of the dependencies include a few `No license found` statements but this should be addressed when we consume the upcoming releases of `bioformats2raw` and `raw2ometiff`

2023-11-30 16:53 UTC, melissalinkert requested changes
Maybe I'm doing something wrong, but if I just run `./gradlew clean build` locally with this PR's branch:

```
> Configure project :
Project : => no module-info.java found

> Task :licenseMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':licenseMain' (type 'LicenseCheck').
  - In plugin 'com.hierynomus.gradle.license.LicenseBasePlugin' type 'com.hierynomus.gradle.license.tasks.LicenseCheck' property 'header' specifies file '/home/melissa/NGFF-Converter/LICENSE' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.
    
    Please refer to https://docs.gradle.org/7.3.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
8 actionable tasks: 8 executed
```

2023-11-30 21:46 UTC, sbesson commented
Thanks @melissalinkert, [796f476](https://github.com/glencoesoftware/NGFF-Converter/pull/55/commits/796f476e60275052c9a2aef8c15d4cef76ff2f4f) should fix the issue by limiting the plugin to be executed to the dependency report.

```
./gradlew clean
./gradlew build
./gradlew downloadLicenses
```

should all be functional targets

2023-12-01 16:35 UTC, melissalinkert approved these changes
`./gradlew clean build` works without error. `./gradlew downloadLicenses` also runs without error, and places report files in `build/reports/license/`.

It does look like only the `dependency-license*`, and not `license-dependency*` files are included in the zip artifact, but I assume that's intentional? As far as I can see both sets of files have the same information, just organized differently.

2023-12-01 17:35 UTC, sbesson commented
Thanks, the choice was definitely intentional. `dependency-license.*` is grouping the information by dependency while `license-dependency*` is grouping the information by license. I found the latter representation to be of limited value while the former has the most useful information for this dependency reporting.

2024-02-16 16:18 UTC, merged